import 'package:flutter/services.dart';
import 'package:share_plus/share_plus.dart';

import '../../learn/models/question_type.dart';
import '../models/test_session.dart';

/// Service for exporting test results
class TestExportService {
  /// Export results as text summary
  static String exportAsText(TestSession session) {
    final buffer = StringBuffer();

    buffer.writeln('═══════════════════════════════════');
    buffer.writeln('          TEST RESULTS');
    buffer.writeln('═══════════════════════════════════');
    buffer.writeln();
    buffer.writeln('📅 Date: ${_formatDate(session.completedAt ?? DateTime.now())}');
    buffer.writeln('⏱️ Duration: ${_formatDuration(session.timeElapsed)}');
    buffer.writeln();
    buffer.writeln('───────────────────────────────────');
    buffer.writeln('              SCORE');
    buffer.writeln('───────────────────────────────────');
    buffer.writeln();
    buffer.writeln('  Grade: ${session.grade}');
    buffer.writeln('  Score: ${session.score.toInt()}%');
    buffer.writeln('  Correct: ${session.correctCount}/${session.totalQuestions}');
    buffer.writeln('  XP Earned: +${session.xpEarned}');
    buffer.writeln();
    buffer.writeln('───────────────────────────────────');
    buffer.writeln('         BY QUESTION TYPE');
    buffer.writeln('───────────────────────────────────');
    buffer.writeln();

    for (final entry in session.breakdownByType.entries) {
      final type = entry.key;
      final breakdown = entry.value;
      buffer.writeln('  ${type.icon} ${type.label}');
      buffer.writeln('     ${breakdown.correct}/${breakdown.total} (${breakdown.accuracy.toInt()}%)');
    }

    buffer.writeln();
    buffer.writeln('───────────────────────────────────');

    if (session.weakTermIds.isNotEmpty) {
      buffer.writeln();
      buffer.writeln('⚠️ ${session.weakTermIds.length} terms need practice');
    }

    buffer.writeln();
    buffer.writeln('═══════════════════════════════════');
    buffer.writeln('     Generated by JpStudy App');
    buffer.writeln('═══════════════════════════════════');

    return buffer.toString();
  }

  /// Copy results to clipboard
  static Future<void> copyToClipboard(TestSession session) async {
    final text = exportAsText(session);
    await Clipboard.setData(ClipboardData(text: text));
  }

  /// Share results using platform share sheet
  static Future<void> shareResults(TestSession session) async {
    final text = exportAsText(session);
    await SharePlus.instance.share(
      ShareParams(text: text),
    );
  }

  /// Export as CSV format
  static String exportAsCSV(TestSession session) {
    final buffer = StringBuffer();

    // Header
    buffer.writeln('Question,Type,Your Answer,Correct Answer,Result,Time (s)');

    // Data rows
    for (int i = 0; i < session.questions.length; i++) {
      final question = session.questions[i];
      final answer = i < session.answers.length ? session.answers[i] : null;

      buffer.writeln([
        i + 1,
        question.type.label,
        '"${answer?.userAnswer ?? ""}"',
        '"${question.correctAnswer}"',
        answer?.isCorrect == true ? 'Correct' : 'Wrong',
        '0', // Time not tracked per question currently
      ].join(','));
    }

    return buffer.toString();
  }

  static String _formatDate(DateTime date) {
    return '${date.year}-${date.month.toString().padLeft(2, '0')}-${date.day.toString().padLeft(2, '0')} '
        '${date.hour.toString().padLeft(2, '0')}:${date.minute.toString().padLeft(2, '0')}';
  }

  static String _formatDuration(Duration duration) {
    final minutes = duration.inMinutes;
    final seconds = duration.inSeconds % 60;
    return '${minutes}m ${seconds}s';
  }
}
